import dotenv from "dotenv";

dotenv.config();

const { DISCORD_TOKEN, DISCORD_CLIENT_ID, GUILD_ID, CLIENT_PUBLIC_KEY, AZURE_COMPUTER_VISION_ENDPOINT, AZURE_COMPUTER_VISION_KEY} = process.env;

if (!DISCORD_TOKEN || !DISCORD_CLIENT_ID || !GUILD_ID || !CLIENT_PUBLIC_KEY || !AZURE_COMPUTER_VISION_ENDPOINT || !AZURE_COMPUTER_VISION_KEY) {
  throw new Error("Missing environment variables");
}

export const config = {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  GUILD_ID,
  CLIENT_PUBLIC_KEY,
  AZURE_COMPUTER_VISION_ENDPOINT,
  AZURE_COMPUTER_VISION_KEY
};
